apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-horcrux
  labels:
    app: horcrux
spec:
  serviceName: horcrux
  replicas: 1
  selector:
    matchLabels:
      app: horcrux
  template:
    metadata:
      labels:
        app: horcrux
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: horcrux
          image: "cosmos/horcrux:latest"
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: horcrux-config
              mountPath: /root/.horcrux
          env:
            - name: SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: horcrux-secrets
                  key: signing_key
          # liveliness and readiness probes
          livenessProbe:
            exec:
              command:
                - horcrux
                - health
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - horcrux
                - status
            initialDelaySeconds: 10
            periodSeconds: 30

      volumes:
        - name: horcrux-config
          persistentVolumeClaim:
            claimName: horcrux-pvc

